#ifndef BITCOIN_CHAINPARAMSSEEDS_H
#define BITCOIN_CHAINPARAMSSEEDS_H
/**
 * List of fixed seed nodes for the Bloodstone network
 * AUTOGENERATED by contrib/seeds/generate-seeds.py
 *
 * Each line contains a BIP155 serialized (networkID, addr, port) tuple.
 *
 * Seeds:
 *   64.188.22.190:17333
 *   192.119.82.145:17333
 */
static const uint8_t chainparams_seed_main[] = {
    0x01,0x04,0x40,0xbc,0x16,0xbe,0x43,0xb5,
    0x01,0x04,0xc0,0x77,0x52,0x91,0x43,0xb5,
};

static const uint8_t chainparams_seed_test[] = {
};
#endif // BITCOIN_CHAINPARAMSSEEDS_H
